### ISSUE TITLE
Enumerate network interfaces

### ISSUE THREAD

**Issue by samatt** [kaganjd/sealion#3]
If this is going to work well we will need to be have clarity on what network interface we are sniffing on.
The names change depending on OS and sometimes hardware. Things that will helkp in the long term

1. Being able to list all network interface
2. Determining what the active network interface (does scapy tell you that?)
3. Getting all the info for the active interface this could include
 - Gateway IP
 - Subnet 
 - Proxy Info if any  

Having this information available will help in the future

**Comment by kaganjd** [comment]
closing since I think this is covered by the getNetworkInfo method
