### ISSUE TITLE
missing link to websocket

### ISSUE THREAD

**Issue by mkeyno** [kaganjd/sealion#37]
Hi, 
I've been trying to reproduce and understand your code, however, I can't find how do you establish WebSocket link and use the ```async def dequeue_packets(ws):``` to deliver msg to ws link
you explanation appreciated

**Comment by kaganjd** [comment]
On the server side, the [websocket](https://github.com/kaganjd/sealion/blob/master/server/src/routes.py#L38) is passed in to the `dequeue_packets` function when it is first called here [server/src/routes.py#L52](https://github.com/kaganjd/sealion/blob/master/server/src/routes.py#L52) or here [server/src/routes.py#L59](https://github.com/kaganjd/sealion/blob/master/server/src/routes.py#L59). 

The websocket is connection is established on the client side when `initSniff()` is called.

The code's pretty messy at the moment, feel free to ask for more clarification if you need!
